Video_rental_LLC/movies/urls.py
from xml.dom import IndexSizeErr
from django.urls import path
from . import views


app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')

]

Video_rental_LLC/video_rental/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls'))
]

Video_rental_LLC/movies/models.py
from email.policy import default
from platform import release
from django.db import models
from django.utils import timezone

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.IntegerField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

Video_rental_LLC/movies/views.py
from curses.ascii import HT
from django.shortcuts import render, get_list_or_404
from django.shortcuts import HttpResponse, Http404
from .models import Movie

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    output = ', '.join([m.title for m in movies])
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):

    movie = get_list_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

Video_rental_LLC/video_rental/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

Video_rental_LLC/movies/templates/movies/detail.html
{% extends 'base.html' %} {% block content %}

<dl>
  <dt>title</dt>
  <dd>{{movie.title}}</dd>
  <dt>Genre</dt>
  <dd>{{movie.genre}}</dd>
  <dt>Stock</dt>
  <dd>{{movie.number_in_stock}}</dd>
</dl>

{% endblock %}

Video_rental_LLC/movies/templates/movies/index.html
{% extends 'base.html' %} {% block content %}

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Stock</th>
      <th>Dayly Rate</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies %}
    <tr>
      <td>
        <a href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a>
      </td>
      <td>{{movie.genre}}</td>
      <td>{{movie.number_in_stock}}</td>
      <td>{{movie.daily_rate}}</td>
      {% endfor %}
    </tr>
  </tbody>
</table>
{% endblock content %}